blank_issues_enabled: false
contact_links:
  - name: Посмотреть существующие обращения
    url: https://github.com/slava225/New-love-plus-Russian-translation-3ds/issues
    about: Возможно, ошибка уже зарегистрирована и для неё найдено решение.
