plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.slava.azljpdownloader'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.slava.azljpdownloader'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '0.3.2'
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
